title: "Payal Godhani"
email: godhanipayal@gmail.com
description: >- 
  A personal site showcasing my talks, blogs, mentorships, patents, and more.
baseurl: "" 
url: "https://godhanipayal.github.io"
theme: jekyll-theme-chirpy  # Choose a theme (you can change this later)
title : Payal Godhani's Space
timeZone : America/Seattle
